// Alert
export const ALERT_CLOSE = 'ALERT_CLOSE';
export const ALERT_FAILED = 'ALERT_FAILED';
export const ALERT_SUCCESS = 'ALERT_SUCCESS';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED'

// Update IP Address
export const UPDATE_IPADDRESS_EDIT = 'UPDATE_IPADDRESS_EDIT'
export const UPDATE_IPADDRESS_REQUEST = 'UPDATE_IPADDRESS_REQUEST'
export const UPDATE_IPADDRESS_COMPLETED = 'UPDATE_IPADDRESS_COMPLETED'
export const UPDATE_IPADDRESS_CANCEL = 'UPDATE_IPADDRESS_CANCEL'
export const UPDATE_IPADDRESS_FAILED = 'UPDATE_IPADDRESS_FAILED'
export const UPDATE_IPADDRESS_SUCCESS = 'UPDATE_IPADDRESS_SUCCESS'

// Create IP Address
export const CREATE_IPADDRESS_NEW = 'CREATE_IPADDRESS_NEW'
export const CREATE_IPADDRESS_CLOSE = 'CREATE_IPADDRESS_CLOSE'
export const CREATE_IPADDRESS_REQUEST = 'CREATE_IPADDRESS_REQUEST'
export const CREATE_IPADDRESS_COMPLETED = 'CREATE_IPADDRESS_COMPLETED'
export const CREATE_IPADDRESS_FAILED = 'CREATE_IPADDRESS_FAILED'
export const CREATE_IPADDRESS_SUCCESS = 'CREATE_IPADDRESS_SUCCESS'